version: '3.3'
services:

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./review/app/.env

  review:
    build: ./review/
    restart: "no"
    depends_on:
      - db
    env_file:
      - ./review/app/.env
  
  bot:
    build: ./bot/
    restart: "no"
    depends_on:
      - db
    env_file:
      - ./bot/review_tracker/.env

  

volumes:
  postgres_data:
